#!/usr/bin/env node
/*
 * Builds index.html: one self-contained file (styles, scripts, the Markdown parser and the example
 * document are all inlined), so the page works when you simply double-click it.
 *
 *   node tools/build.js            write index.html
 *   node tools/build.js --check    exit 1 if index.html is out of date (used by the tests)
 */
'use strict';
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const read = p => fs.readFileSync(path.join(root, p), 'utf8');

const SCRIPTS = ['vendor/marked.umd.js', 'src/tables.js', 'src/preamble.js', 'src/md2tex.js', 'src/zip.js', 'src/app.js'];

/** Make JavaScript safe to place inside an HTML <script> element. */
function inlineJs(code) {
  return code
    .replace(/<\/(script)/gi, '<\\/$1')       // would end the element early
    .replace(/<!--/g, '<\\x21--');            // would start the "escaped script" state
}

function build() {
  let html = read('src/index.template.html');
  const sample = read('examples/sample.md');
  const parts = SCRIPTS.map(file => {
    let code = read(file);
    if (file === 'src/app.js') {
      if (!code.includes("/*__SAMPLE_MD__*/ ''")) throw new Error('sample placeholder missing in app.js');
      // a replacer function: a plain string would treat "$$" and "$&" in the sample as special patterns
      const json = JSON.stringify(sample).replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
      code = code.replace("/*__SAMPLE_MD__*/ ''", () => json);
    }
    return '<script>\n// ' + file + '\n' + inlineJs(code.replace(/\n\/\/# sourceMappingURL=.*$/m, '')) + '\n</script>';
  });
  if (!html.includes('/*__CSS__*/') || !html.includes('<!--__SCRIPTS__-->')) throw new Error('template placeholders missing');
  html = html.replace('/*__CSS__*/', () => read('src/style.css'));
  html = html.replace('<!--__SCRIPTS__-->', () => parts.join('\n'));
  html = html.replace('<!doctype html>', '<!doctype html>\n<!-- Generated by tools/build.js from src/. Edit the files in src/ and run: node tools/build.js -->');
  return html;
}

if (require.main === module) {
  const out = path.join(root, 'index.html');
  const html = build();
  if (process.argv.includes('--check')) {
    const current = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : '';
    if (current !== html) { console.error('index.html is out of date: run node tools/build.js'); process.exit(1); }
    console.log('index.html is up to date');
  } else {
    fs.writeFileSync(out, html);
    console.log('wrote index.html (' + (html.length / 1024).toFixed(0) + ' KB)');
  }
}

module.exports = { build };
